---
development:
  DB_FILENAME: 'app/infrastructure/database/local/dev.db'
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token

test:
  DB_FILENAME: 'app/infrastructure/database/local/test.db'
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token

production:
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token